name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # regenerates daily
  workflow_dispatch:        # lets you trigger it manually
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Stats card
        uses: lowlighter/metrics@latest
        with:
          filename: github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Reigns-B
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Nairobi

      - name: Generate Activity Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: github-activity.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Reigns-B
          template: classic
          base: header
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
